const nameGirl = 'To:Thanh Quynh';
const giftUrl = 'https://www.facebook.com/groups/165460116804572';
const eventName = 'Happy 8/3 !!!';
const titleCard = 'For Thanh Quynh';
const contentCard = '</br> Chào cô công chúa của tiểu vương quốc</br> Anh rất vui khi được quen biết em. </br> Chúng ta chưa từng gặp nhau nhưng ngày đó không xa chút nào, và tất nhiên là những thứ đã hứa tặng em chứ nhỉ :3. </br>Ngày Quốc tế Phụ nữ, chúc em luôn xinh đẹp, hạnh phúc và vui vẻ không chỉ vào ngày 8/3 và cả những ngày khác nữa. Giữ gìn sức khỏe nha <3 </br></br> From 07.29 with luv';
const giftImage = 'thanhquynh.jpg';
const giftBg = 'valentines.jpg'
const base64 = '';
const giftImageBase64 = "data:image/jpg;base64, " + base64;